// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package movieapp.proxies;

public class Movies
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject moviesMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MovieApp.Movies";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		ProductionStartYear("ProductionStartYear"),
		ProductionFinishedYear("ProductionFinishedYear");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Movies(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MovieApp.Movies"));
	}

	protected Movies(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject moviesMendixObject)
	{
		if (moviesMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MovieApp.Movies", moviesMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MovieApp.Movies");

		this.moviesMendixObject = moviesMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Movies.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static movieapp.proxies.Movies initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return movieapp.proxies.Movies.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static movieapp.proxies.Movies initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new movieapp.proxies.Movies(context, mendixObject);
	}

	public static movieapp.proxies.Movies load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return movieapp.proxies.Movies.initialize(context, mendixObject);
	}

	public static java.util.List<movieapp.proxies.Movies> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<movieapp.proxies.Movies> result = new java.util.ArrayList<movieapp.proxies.Movies>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MovieApp.Movies" + xpathConstraint))
			result.add(movieapp.proxies.Movies.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of ProductionStartYear
	 */
	public final java.lang.Integer getProductionStartYear()
	{
		return getProductionStartYear(getContext());
	}

	/**
	 * @param context
	 * @return value of ProductionStartYear
	 */
	public final java.lang.Integer getProductionStartYear(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ProductionStartYear.toString());
	}

	/**
	 * Set value of ProductionStartYear
	 * @param productionstartyear
	 */
	public final void setProductionStartYear(java.lang.Integer productionstartyear)
	{
		setProductionStartYear(getContext(), productionstartyear);
	}

	/**
	 * Set value of ProductionStartYear
	 * @param context
	 * @param productionstartyear
	 */
	public final void setProductionStartYear(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer productionstartyear)
	{
		getMendixObject().setValue(context, MemberNames.ProductionStartYear.toString(), productionstartyear);
	}

	/**
	 * @return value of ProductionFinishedYear
	 */
	public final java.lang.Integer getProductionFinishedYear()
	{
		return getProductionFinishedYear(getContext());
	}

	/**
	 * @param context
	 * @return value of ProductionFinishedYear
	 */
	public final java.lang.Integer getProductionFinishedYear(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ProductionFinishedYear.toString());
	}

	/**
	 * Set value of ProductionFinishedYear
	 * @param productionfinishedyear
	 */
	public final void setProductionFinishedYear(java.lang.Integer productionfinishedyear)
	{
		setProductionFinishedYear(getContext(), productionfinishedyear);
	}

	/**
	 * Set value of ProductionFinishedYear
	 * @param context
	 * @param productionfinishedyear
	 */
	public final void setProductionFinishedYear(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer productionfinishedyear)
	{
		getMendixObject().setValue(context, MemberNames.ProductionFinishedYear.toString(), productionfinishedyear);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return moviesMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final movieapp.proxies.Movies that = (movieapp.proxies.Movies) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MovieApp.Movies";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
