// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package movieapp.proxies;

public class Plot
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject plotMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MovieApp.Plot";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Plot("Plot"),
		WrittenBy("WrittenBy"),
		Plot_Movies("MovieApp.Plot_Movies");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Plot(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MovieApp.Plot"));
	}

	protected Plot(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject plotMendixObject)
	{
		if (plotMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MovieApp.Plot", plotMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MovieApp.Plot");

		this.plotMendixObject = plotMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Plot.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static movieapp.proxies.Plot initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return movieapp.proxies.Plot.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static movieapp.proxies.Plot initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new movieapp.proxies.Plot(context, mendixObject);
	}

	public static movieapp.proxies.Plot load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return movieapp.proxies.Plot.initialize(context, mendixObject);
	}

	public static java.util.List<movieapp.proxies.Plot> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<movieapp.proxies.Plot> result = new java.util.ArrayList<movieapp.proxies.Plot>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MovieApp.Plot" + xpathConstraint))
			result.add(movieapp.proxies.Plot.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Plot
	 */
	public final java.lang.String getPlot()
	{
		return getPlot(getContext());
	}

	/**
	 * @param context
	 * @return value of Plot
	 */
	public final java.lang.String getPlot(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Plot.toString());
	}

	/**
	 * Set value of Plot
	 * @param plot
	 */
	public final void setPlot(java.lang.String plot)
	{
		setPlot(getContext(), plot);
	}

	/**
	 * Set value of Plot
	 * @param context
	 * @param plot
	 */
	public final void setPlot(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String plot)
	{
		getMendixObject().setValue(context, MemberNames.Plot.toString(), plot);
	}

	/**
	 * @return value of WrittenBy
	 */
	public final java.lang.String getWrittenBy()
	{
		return getWrittenBy(getContext());
	}

	/**
	 * @param context
	 * @return value of WrittenBy
	 */
	public final java.lang.String getWrittenBy(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WrittenBy.toString());
	}

	/**
	 * Set value of WrittenBy
	 * @param writtenby
	 */
	public final void setWrittenBy(java.lang.String writtenby)
	{
		setWrittenBy(getContext(), writtenby);
	}

	/**
	 * Set value of WrittenBy
	 * @param context
	 * @param writtenby
	 */
	public final void setWrittenBy(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String writtenby)
	{
		getMendixObject().setValue(context, MemberNames.WrittenBy.toString(), writtenby);
	}

	/**
	 * @return value of Plot_Movies
	 */
	public final movieapp.proxies.Movies getPlot_Movies() throws com.mendix.core.CoreException
	{
		return getPlot_Movies(getContext());
	}

	/**
	 * @param context
	 * @return value of Plot_Movies
	 */
	public final movieapp.proxies.Movies getPlot_Movies(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		movieapp.proxies.Movies result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Plot_Movies.toString());
		if (identifier != null)
			result = movieapp.proxies.Movies.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Plot_Movies
	 * @param plot_movies
	 */
	public final void setPlot_Movies(movieapp.proxies.Movies plot_movies)
	{
		setPlot_Movies(getContext(), plot_movies);
	}

	/**
	 * Set value of Plot_Movies
	 * @param context
	 * @param plot_movies
	 */
	public final void setPlot_Movies(com.mendix.systemwideinterfaces.core.IContext context, movieapp.proxies.Movies plot_movies)
	{
		if (plot_movies == null)
			getMendixObject().setValue(context, MemberNames.Plot_Movies.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Plot_Movies.toString(), plot_movies.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return plotMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final movieapp.proxies.Plot that = (movieapp.proxies.Plot) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MovieApp.Plot";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
